const QUESTIONS = [
  {
    "question_level_id": 1,
    "question": "What is the biggest city in the world?",
    "answers": "Rio de Janeiro, Berlin, Tokyo, Beijing",
    "question_pt": "Qual é a maior cidade do mundo?",
    "answers_pt": "Rio de Janeiro, Berlin, Tokyo, Beijing",
    "correct": 2,
  },
  {
    "question_level_id": 1,
    "question": "What's the biggest animal in the world?",
    "answers": "Tiger, Giraffe, Pig, Blue Whale",
    "question_pt": "Qual o maior animal do mundo?",
    "answers_pt": "Tigre, Girafa, Porco, Baleia Azul",
    "correct": 3,
  },
  {
    "question_level_id": 1,
    "question": "Who painted the Mona Lisa?",
    "answers":
        "Michelangelo, Leonardo da Vinci, Pablo Picasso, Leonardo DiCaprio",
    "question_pt": "Quem pintou Mona Lisa?",
    "answers_pt":
        "Michelangelo, Leonardo da Vinci, Pablo Picasso, Leonardo DiCaprio",
    "correct": 1,
  },
  {
    "question_level_id": 1,
    "question": "What is the capital of Iceland?",
    "answers": "Mývatn, Vik, Reykjavík, Norway",
    "question_pt": "Qual a capital da Islândia?",
    "answers_pt": "Mývatn, Vik, Reykjavík, Norway",
    "correct": 2,
  },
  {
    "question_level_id": 1,
    "question": "Which planet is closest to the sun?",
    "answers": "Earth, Mars, Jupiter, Mercury",
    "question_pt": "Qual o planeta mais próximo do sol?",
    "answers_pt": "Terra, Marte, Júpiter, Mercúrio",
    "correct": 3,
  },
  {
    "question_level_id": 1,
    "question": "What is the largest country in the world?",
    "answers": "Japan, India, Russia, China",
    "question_pt": "Qual o maior país do mundo?",
    "answers_pt": "Japão, India, Russia, China",
    "correct": 2,
  },
  {
    "question_level_id": 1,
    "question": "How many valves does the heart have?",
    "answers": "4, 1, 5, 3",
    "question_pt": "Quantas válvulas o coração tem?",
    "answers_pt": "4, 1, 5, 3",
    "correct": 0,
  },
  {
    "question_level_id": 1,
    "question": "In Harry Potter, what is the name of The Weasley's house?",
    "answers": "Shell Cottage, Spinner's End, The Burrow, Durmstrang",
    "question_pt": "Em Harry Potter, qual é o nome da casa dos Weasley's?",
    "answers_pt": "Shell Cottage, Spinner's End, The Burrow, Durmstrang",
    "correct": 2,
  },
  {
    "question_level_id": 1,
    "question": "What's a baby rabbit called?",
    "answers": "Kitten, Pup, Bunny, Mutt",
    "question_pt": "Como um bebê coelho é chamado?",
    "answers_pt": "Coelhinho, Filhote, Gatinho, Vira-lata",
    "correct": 0,
  },
  {
    "question_level_id": 1,
    "question": "How many elements are there in the periodic table?",
    "answers": "224, 118, 72, 116",
    "question_pt": "Quantos elementos tem na tabela periódica?",
    "answers_pt": "224, 118, 72, 116",
    "correct": 1,
  },
];
